version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices_net

  orders_service:
    build: ./orders_service
    container_name: orders_service
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - microservices_net

  notifications_service:
    build: ./notifications_service
    container_name: notifications_service
    env_file: .env
    depends_on:
      - rabbitmq
    networks:
      - microservices_net

volumes:
  rabbitmq_data:

networks:
  microservices_net:
    driver: bridge
